const mongoose = require('mongoose');
const uuidv4 = require('uuid/v4');
const schemaCreator = require('../../utilities/schemaCreator');

const schema = schemaCreator.createSchema(
  {
    _id: {
      type: String,
      default: uuidv4,
    },
    /**
     * @name userId
     * @desc The user identifier of the inviter.
     * @type String
     * @memberof ReferralInvitation
     * @required
     * @inner
     */
    userId: {
      type: String,
      default: null,
    },
    /**
     * @name email
     * @desc Email of the invited person.
     * @type String
     * @memberof ReferralInvitation
     * @inner
     */
    email: {
      type: String,
      default: null,
    },
    /**
     * @name phone
     * @desc Phone of the invited person.
     * @type String
     * @memberof ReferralInvitation
     * @inner
     */
    phone: {
      type: String,
      default: null,
    },
    /**
     * @name claimed
     * @desc Flag indicating if the user claimed the reward.
     * @type Boolean
     * @memberof ReferralInvitation
     * @inner
     */
    claimed: {
      type: Boolean,
      default: false,
    },
    /**
     * @name invitedUserId
     * @desc The user identifier of the invited user.
     * @type String
     * @memberof ReferralInvitation
     * @inner
     */
    invitedUserId: {
      type: String,
      default: null,
    },
    /**
     * @name token
     * @desc Token generated by Platform-Core API, to validate Branch.io webhooks.
     * @type String
     * @memberof ReferralInvitation
     * @required
     * @inner
     */
    token: {
      type: String,
      required: true,
    },
    /**
     * @name partner
     * @desc Flag indicating if it is a partner campaign.
     * @type Boolean
     * @memberof ReferralInvitation
     * @inner
     */
    partner: {
      type: Boolean,
      default: false,
    },
    /**
     * @name campaign
     * @desc The campaign identifier.
     * @type String
     * @memberof ReferralInvitation
     * @inner
     */
    campaign: {
      type: String,
      default: null,
    },
  },
  {
    versionKey: false,
    timestamps: true,
  },
);

/**
 * @namespace ReferralInvitation
 * @name ReferralInvitation
 * @desc ReferralInvitation model maps to a MongoDB collection and defines the shape of the document.
 *
 * @param schema
 * @type {Model}
 */
module.exports = mongoose.model('ReferralInvitation', schema);
